### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pavolfranekdev** [Bunlong/svelte-csv#1]
The requested module '/node_modules/papaparse/papaparse.min.js?v=8573111b' does not provide an export named 'default'
SyntaxError: The requested module '/node_modules/papaparse/papaparse.min.js?v=8573111b' does not provide an export named 'default'

**Comment by pavolfranekdev** [comment]
@Bunlong any idea?

**Comment by Bunlong** [comment]
@pavolfranekdev I will check it and let you know soon.

**Comment by pavolfranekdev** [comment]
@Bunlong thanks I'll be waiting

**Comment by andyburke** [comment]
Getting the same thing. Tried adding 'papaparse' to vite's optimizeDeps.exclude, still no joy.

**Comment by Snailedlt** [comment]
Same issue here

**Comment by Bunlong** [comment]
@pavolfranekdev @andyburke @Snailedlt bug was fixed in v1.2.8 and please follow the [note](https://github.com/Bunlong/svelte-csv#%E2%84%B9%EF%B8%8F-note-on-usage-with-sveltekit).

**Comment by jrmoynihan** [comment]
@Bunlong I'm still having this issue.  optimizeDeps didn't fix this.
